name: Lint and Test Checks

on:
  push:
    branches:
      - "*"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} 🔧
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install Dependencies 🔧
        run: yarn

      - name: Run Lint 🔧
        run: yarn lint

      - name: Run Test 🔧
        run: yarn test

  build-package-publish-to-npm:
    needs: lint-test
    if: ${{ success() && github.repository == 'upnotes-io/react-todo' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Use Node.js ${{ matrix.node-version }} 🔧
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install and Build Package 🔧
        run: |
          yarn
          yarn build

      - name: Publish to NPMJS 🚀
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-storybook-deploy-to-gh-pages:
    needs: lint-test
    if: ${{ success() && github.repository == 'upnotes-io/react-todo' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Use Node.js ${{ matrix.node-version }} 🔧
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install and Build Storybook 🔧
        run: |
          yarn
          yarn build

      - name: Deploy Storybook to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          clean: true
          branch: gh-pages # The branch the action should deploy to.
          folder: .out # The folder the action should deploy.
          ssh-key: ${{ secrets.DEPLOY_KEY }} # using ssh key as token does not have permission to build gh-pages - https://github.com/JamesIves/github-pages-deploy-action/tree/dev#using-an-ssh-deploy-key-
